--1:
SELECT FIRST_NAME, SALARY FROM HR.EMPLOYEES

--2:
SELECT FIRST_NAME, SALARY FROM HR.EMPLOYEES
WHERE SALARY > 20

--3:
SELECT FIRST_NAME, SALARY FROM HR.EMPLOYEES
ORDER BY SALARY DESC

--4:
SELECT FIRST_NAME, SALARY FROM HR.EMPLOYEES
ORDER BY SALARY DESC
LIMIT 5

--5:
SELECT LOCATION_ID, CITY, COUNTRY_ID FROM HR.LOCATIONS
WHERE COUNTRY_ID = 'US'
ORDER BY CITY ASC
LIMIT 5

--1:
SELECT j.JOB_ID, d.DEPARTMENT_NAME AS CustomerName, e.FIRST_NAME, e.LAST_NAME, j.START_DATE FROM HR.JOB_HISTORY j
INNER JOIN HR.DEPARTMENTS d ON j.DEPARTMENT_ID = d.DEPARTMENT_ID
INNER JOIN HR.EMPLOYEES e ON j.EMPLOYEE_ID = e.EMPLOYEE_ID

--2:
SELECT j.JOB_ID, e.FIRST_NAME, r.REGION_NAME, e.SALARY, e.COMMISSION_PCT FROM HR.JOB_HISTORY j
INNER JOIN HR.EMPLOYEES e ON j.EMPLOYEE_ID = e.EMPLOYEE_ID
INNER JOIN HR.DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
INNER JOIN HR.LOCATIONS l ON d.LOCATION_ID = l.LOCATION_ID;

--3:
SELECT l.LOCATION_ID, l.CITY, COUNT(e.EMPLOYEE_ID) AS TotalOrders FROM HR.LOCATIONS l
LEFT JOIN HR.DEPARTMENTS d ON l.LOCATION_ID = d.LOCATION_ID
LEFT JOIN HR.EMPLOYEES e ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
GROUP BY l.LOCATION_ID, l.CITY;

--4:
SELECT e.FIRST_NAME AS EmployeeFirstName, e.LAST_NAME AS EmployeeLastName, m.FIRST_NAME AS ManagerFirstName, m.LAST_NAME AS ManagerLastName FROM HR.EMPLOYEES e
LEFT JOIN HR.EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID;

--1:
SELECT l.LOCATION_ID, l.CITY, SUM(e.SALARY) AS TotalRevenue FROM HR.LOCATIONS l
JOIN HR.DEPARTMENTS d ON l.LOCATION_ID = d.LOCATION_ID
JOIN HR.EMPLOYEES e ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
GROUP BY l.LOCATION_ID, l.CITY
ORDER BY TotalRevenue DESC
LIMIT 5;

--2:
SELECT e.HIRE_DATE, COUNT(e.EMPLOYEE_ID) AS TotalOrders FROM HR.EMPLOYEES e
GROUP BY e.HIRE_DATE;

--3:
SELECT DEPARTMENT_ID AS CategoryID, AVG(SALARY) AS AvgPrice FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) > 25;

--4:
SELECT MANAGER_ID AS CustomerID, COUNT(EMPLOYEE_ID) AS TotalOrders FROM HR.EMPLOYEES
GROUP BY MANAGER_ID
HAVING COUNT(EMPLOYEE_ID) > 10;

--1:
SELECT FIRST_NAME AS ProductName, SALARY AS UnitPrice FROM HR.EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM HR.EMPLOYEES);

--2:
WITH CustomerSales AS (
    SELECT e.MANAGER_ID AS CustomerID, SUM(e.SALARY * NVL(e.COMMISSION_PCT, 1)) AS TotalSpent
    FROM HR.EMPLOYEES e
    GROUP BY e.MANAGER_ID
)
SELECT m.FIRST_NAME AS CompanyName, cs.TotalSpent FROM CustomerSales cs
JOIN HR.EMPLOYEES m ON cs.CustomerID = m.EMPLOYEE_ID
ORDER BY cs.TotalSpent DESC;

--1:
SELECT MANAGER_ID AS CustomerID, EMPLOYEE_ID AS OrderID, HIRE_DATE AS OrderDate,
ROW_NUMBER() OVER (PARTITION BY MANAGER_ID ORDER BY HIRE_DATE) AS CustomerOrderSeq
FROM HR.EMPLOYEES;

--2:
SELECT DEPARTMENT_ID AS CategoryID, FIRST_NAME AS ProductName, SALARY AS UnitPrice,
RANK() OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) AS PriceRank
FROM HR.EMPLOYEES;

--3:
SELECT EMPLOYEE_ID AS OrderID, HIRE_DATE AS OrderDate, SALARY AS Freight,
SUM(SALARY) OVER (ORDER BY HIRE_DATE, EMPLOYEE_ID) AS RunningTotalFreight
FROM HR.EMPLOYEES;

--1:
CREATE INDEX idx_customers_country ON HR.LOCATIONS (COUNTRY_ID);

--2:
SELECT d.DEPARTMENT_ID AS CustomerID, d.DEPARTMENT_NAME AS CompanyName,
(SELECT COUNT(e.EMPLOYEE_ID) FROM HR.EMPLOYEES e WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID) AS OrderCount
FROM HR.DEPARTMENTS d;

--3:
SELECT d.DEPARTMENT_ID AS CustomerID, d.DEPARTMENT_NAME AS CompanyName, COUNT(e.EMPLOYEE_ID) AS OrderCount
FROM HR.DEPARTMENTS d
LEFT JOIN HR.EMPLOYEES e ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_ID, d.DEPARTMENT_NAME;